package com.swachhtrack.service;

import com.swachhtrack.entity.Complaint;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
@Slf4j
public class AIContentService {

    public String generateAwarenessContent(Complaint complaint) {
        return "Please keep this area clean. A waste issue was reported at " +
                complaint.getAddress() + " on " + complaint.getCreatedAt().toLocalDate() +
                ". Kindly dispose waste responsibly.";
    }

    public String generateEscalationContent(Complaint complaint) {
        log.info("Generating escalation content for complaint ID: {}", complaint.getId());

        long hoursPending = Duration.between(complaint.getCreatedAt(), LocalDateTime.now()).toHours();

        StringBuilder content = new StringBuilder();
        content.append("=== ESCALATION NOTICE ===\n\n");
        content.append("Complaint ID: #").append(complaint.getId()).append("\n");
        content.append("Location: ").append(extractLocationName(complaint.getAddress())).append("\n");
        content.append("Reported On: ").append(
                complaint.getCreatedAt().format(DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm"))).append("\n");
        content.append("Hours Pending: ").append(hoursPending).append(" hours\n\n");

        content.append("REASON FOR ESCALATION:\n");
        content.append("This complaint has remained unresolved for over 48 hours. ");
        content.append("Despite being assigned to the responsible ward in-charge, ");
        content.append("no action has been initiated on this waste dumping issue.\n\n");

        content.append("SUGGESTED ACTIONS:\n");
        content.append("1. Immediate field inspection by senior waste management officer\n");
        content.append("2. Deploy cleaning crew within 24 hours\n");
        content.append("3. Provide status update to the citizen\n");
        content.append("4. Document reasons for delay in resolution\n\n");

        content.append("PUBLIC AWARENESS MESSAGE:\n");
        content.append(generateAwarenessContent(complaint));

        content.append("\n\n--- Generated by SwachhTrack AI Assistant ---");

        String finalContent = enhanceContentWithAI(content.toString());

        log.info("Escalation content generated for complaint ID: {}", complaint.getId());
        return finalContent;
    }

    private String extractLocationName(String address) {
        if (address == null || address.isBlank()) {
            return "Unknown Location";
        }
        return address.split(",")[0].trim();
    }

    private String enhanceContentWithAI(String content) {
        return content;
    }
}
